### PR TITLE
20240311 sl document review

### PR DESCRIPTION
**Pull request by Sandy-Labuschagne**
Readme.md language changes for review

### CODE REVIEW

**Comment by Justus-at-Tazama** [comment]
When creating an acronym for a plural, see if there's a way to pluralise the acronym, e.g. Financial Service Providers (FSPs).

**Comment by Justus-at-Tazama** [comment]
Modern grammatical style is to append an "s" to an acronym for a plural without an apostrophe, e.g. FSPs and not FSP's, which would denote possession by the FSP instead.

**Comment by Justus-at-Tazama** [comment]
There is some confusion in our use of DFPS vs FSP. Initially, we borrowed the DFSP (Digital Financial Service Provider) from Mojaloop since they were largely and almost exclusively focused on the Digital part of the ecosystem. We have since decided to remove the "Digital" and the "D" because we felt our focus was more universal.

**Comment by Sandy-Labuschagne** [comment]
Should all references to DFSP be changed to FSP?

**Comment by Justus-at-Tazama** [comment]
> Should all references to DFSP be changed to FSP?

Yes, eventually. We'll update as we go.

**Review by Justus-at-Tazama — APPROVED** [review]

**Pull request merged**
